### ISSUE TITLE
Does this algorithm work for open surfaces?

### ISSUE THREAD

**Issue by Oleginnn** [cheind/mesh-deform#2]
By open surface I mean the triangle mesh with border edges.

When I try to deform my mesh,  setupLinearSystem() doesn't solve.
That is  why I am wondering, it happens because my mesh is open, flat piece of surface, not like sphere in you example.

Thank you,
Oleg

**Comment by cheind** [comment]
Yes that can indeed be a problem, although I have never tested it explicitly. It's been some time since I programmed it, so I'm quite unsure right now how fix it. Maybe all that it needs is to avoid adding faces with border edges to the equation system. 

Start here:
https://github.com/cheind/mesh-deform/blob/master/inc/deform/arap.h#L149

I guess you will need to also change vertex handling when you leave out faces.
